piqi:
	piqi of-proto -I ./pb/ ./pb/riak.proto -o ./riak.proto.piqi
	piqi of-proto -I ./pb/ ./pb/riak_kv.proto -o ./riak_kv.proto.piqi
	piqi of-proto -I ./pb/ ./pb/riak_search.proto -o ./riak_search.proto.piqi
	cat riak.piqi.additions >> riak.proto.piqi
	piqic ocaml-ext --pp riak.proto.piqi
	piqic ocaml-ext --pp riak_kv.proto.piqi
	piqic ocaml-ext --pp riak_search.proto.piqi
